% Startup tasks informations
fprintf('Find PRTools alternatives to already implemented methods.\n')
fprintf('Error printing in listSettingsResults\n')
fprintf('Improve methods by using CV during training?\n')
fprintf('Documentation\n')
fprintf('RDA speed up\n')

fprintf('\nMost recent: \n')
fprintf('    Is Fisher similar to LDC?\n')
fprintf('    ANN - good settings\n')
fprintf('    RBF - good settings\n')
fprintf('    Implement all Arbabshirani''s methods.\n')
fprintf('    Prepare testing kit for multiple machines\n')
fprintf('    RDA making functional')
fprintf('    Boosting strategies\n')