% Startup tasks informations
fprintf('Find PRTools alternatives to already implemented methods.\n')
fprintf('Generating TeX files with results\n')
fprintf('Documentation\n')
fprintf('RDA speed up and functionality\n')
fprintf('Labels in column or independent?\n')
fprintf('Split MATLAB and PRTools settings?\n')
fprintf('Improve multilevel gridsearch. Use regoptc in PRTools?\n')
fprintf('Improve network architecture gridsearch in trainCVClassifier\n')
fprintf('ANN, RBF - good settings - Filip Dechterenko?\n')

fprintf('\nMost recent: \n')
fprintf('    Verify if qda in prtools has so good results\n')
fprintf('    Write superclass for linear and svmtrees\n')
fprintf('    Adjust classifier settings according to matlab version\n')
fprintf('    Boosting strategies\n')